### ISSUE TITLE
Unable to set Congito userpool username to case insensitive

### ISSUE THREAD

**Issue by douglas-gibbons-lark** [awslabs/goformation#310] opened 2020-09-23 18:19 UTC
Similar to #61, "False" values are omitted, which leads to problems trying to set cognito.UserPool_UsernameConfiguration.CaseSensitive to false.

**Example**

```golang
package main

import (
	"io/ioutil"

	"github.com/awslabs/goformation/v4/cloudformation"
	"github.com/awslabs/goformation/v4/cloudformation/cognito"
)

func main() {
	c := &cognito.UserPool{
		UsernameConfiguration: &cognito.UserPool_UsernameConfiguration{
			CaseSensitive: false,
		},
	}
	t := cloudformation.NewTemplate()
	t.Resources["myCognito"] = c

	j, _ := t.JSON()
	ioutil.WriteFile("/tmp/stack.json", j, 0644)
}

```

Gives:
```json
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Resources": {
    "myCognito": {
      "Properties": {
        "UsernameConfiguration": {}
      },
      "Type": "AWS::Cognito::UserPool"
    }
  }
}
```

Which leads to cloudformation error:
```
Value null at 'usernameConfiguration.caseSensitive' failed to satisfy constraint
```

**Fix(?)**

Changing cloudformation/cognito/aws-cognito-userpool_usernameconfiguration.go

```
CaseSensitive bool `json:"CaseSensitive,omitempty"`
```

to 

```
CaseSensitive bool `json:"CaseSensitive"`
```

fixed it for me, but not sure if this breaks anything else?

**Comment by xrn** [comment] 2020-09-24 08:12
Looks like documentation is incorrect - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html looking on your template and error in AWS documentation `CaseSensitive` should be `Required: Yes`

**Comment by douglas-gibbons-lark** [comment] 2020-10-05 21:33
Thanks @xrn - do we need to wait for the documentation to be updated before this can be fixed?

**Comment by PaulMaddox** [comment] 2020-10-12 07:56
+1 on xrn's comment here. This is being caused by the `CaseSensitive` field being marked as optional in the 
[AWS CloudFormation Resource Specification](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/cfn-resource-specification.html): 

```json
"AWS::Cognito::UserPool.UsernameConfiguration": {
    "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html",
    "Properties": {
        "CaseSensitive": {
            "Required": false,
            "Documentation": "http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-usernameconfiguration.html#cfn-cognito-userpool-usernameconfiguration-casesensitive",
            "PrimitiveType": "Boolean",
            "UpdateType": "Mutable"
        }
    }
},
```


As a result of this, goformation is adding the `omitempty` json tag to the struct field, which in turn leads to 'false' ([the default "empty" value of a boolean in go](https://yourbasic.org/golang/default-zero-value/)) being omitted from the final generated template.

The CloudFormation team have acknowledged the specification error in the issue that @xrn opened. The only workaround I can think of at the moment is to fork goformation, and manually remove the `omitempty` tag. We can't do this in the main library repo as it would be overwritten (the whole library is autogenerated on a daily basis from the CloudFormation spec).

**Comment by rubenfonseca** [comment] 2022-07-18 08:23
Correct, thank you!

**Closed by rubenfonseca** 2022-07-18 08:23 UTC
Labels: awaiting-upstream

**Comment by douglas-gibbons-lark** [comment] 2022-08-27 00:04
Thank you all for keeping this one alive. I can also confirm that V6 works.
